# -*- coding: utf-8 -*-
"""FA4_Patayon_APM1220.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VHVhjYLdj7ssotjEn3xHtM0wF05WfpR4

# Formative Assessment 4
## APM1220 - Applied Multivariate Data Analysis
Prepared by: Spike Lee-Roy V. Patayon

---

Import necessary libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy import stats
from matplotlib.patches import Rectangle

"""### 1. Hotelling’s $T^2$ Test for a Mean Vector

Given the data matrix $X$:

$$X = \begin{bmatrix} 2 & 12 \\ 8 & 9 \\ 6 & 9 \\ 8 & 10 \end{bmatrix}$$

(a) Evaluate $T^2$ for testing the null hypothesis $H_0 : \mathbf{\mu}' = \begin{bmatrix} 7 & 11 \end{bmatrix}$.

(b) Specify the exact distribution of $T^2$ under the null hypothesis for this situation.

(c) Using parts (a) and (b), test $H_0$ at the significance level $\alpha = 0.05$. What statistical conclusion do you reach?
"""

X = np.array([
    [2, 12],
    [8, 9],
    [6, 9],
    [8, 10]
])

n, p = X.shape
print(f'Number of observation: {n}')
print(f'Number of variables: {p}')

x_bar = np.mean(X, axis = 0)
print(f'\nSample mean: \n{x_bar}')

S = np.cov(X, rowvar = False)
print(f'\nCovariance matrix:\n{S}')

# hypothesized population mean vector
mu0 = np.array([7, 11])
print(f'\nHypothesized population mean vector: \n{mu0}')
difference = x_bar - mu0
print(f'\nDifference between sample mean and hypothesized population mean vector: \n{difference}')

# inverse covariance matrix
s_inv = np.linalg.inv(S)
print(f'\nInverse of covariance matrix: \n{s_inv}')

# hotelling T^2
T2  = n * difference @ s_inv @ difference.T
print(f'\nHotelling T^2: {T2:.2f}')

print('\nConverting Hotelling T^2 to F statistics:')
F_stat = ((n-p)/(p*(n-1))) * T2
print(f'F-statistic: {F_stat:.2f}')

print('\nCritical F:')
alpha = 0.05
F_critical = stats.f.ppf(1-alpha, p, n-p)
print(f'F-critical: {F_critical:.2f}')

# p value
p_value = 1 - stats.f.cdf(F_stat, p, n-p)
print(f'\nP-value: {p_value:.2f}')

if p_value < alpha:
  print('\nReject null hypothesis')
else:
  print('\nFail to reject null hypothesis')

"""The sample mean vector was $\bar{\mathbf{x}}' = [6, 10]$, and Hotelling's $T^2$ statistic for testing $H_0 : \boldsymbol{\mu}' = [7, 11]$ was $T^2 = 13.6364$. Transforming the statistic gives $F = 4.5455$, which under the null hypothesis follows an $F_{2,2}$ distribution. The corresponding $p$-value is approximately $0.1803$. Since $p > 0.05$, the null hypothesis is not rejected at the 5% significance level. Thus, the sample does not provide sufficient evidence that the population mean vector differs from $[7, 11]'$.

---

### 2. Simultaneous Confidence Intervals and Regions for Grizzly Bear Body Measurements

Harry Roberts, a naturalist for the Alaska Fish and Game department, studies grizzly bears with the goal of maintaining a healthy population. Measurements on $n = 61$ bears provided the following summary statistics:

| Variable | Weight (kg) | Body length (cm) | Neck (cm) | Girth (cm) | Head length (cm) | Head width (cm) |
|---|---|---|---|---|---|---|
| **Sample mean $\bar{\mathbf{x}}$** | 95.52 | 164.38 | 55.69 | 93.39 | 17.98 | 31.13 |

**Covariance matrix $\mathbf{S}$:**

$$\mathbf{S} = \begin{bmatrix}
3266.46 & 1343.97 & 731.54 & 1175.50 & 162.68 & 238.37 \\
1343.97 & 721.91 & 324.25 & 537.35 & 80.17 & 117.73 \\
731.54 & 324.25 & 179.28 & 281.17 & 39.15 & 56.80 \\
1175.50 & 537.35 & 281.17 & 474.98 & 63.73 & 94.85 \\
162.68 & 80.17 & 39.15 & 63.73 & 9.95 & 13.88 \\
238.37 & 117.73 & 56.80 & 94.85 & 13.88 & 21.26
\end{bmatrix}$$

(a) Obtain the large-sample 95% simultaneous confidence intervals for the six population mean body measurements.

(b) Obtain the large-sample 95% simultaneous confidence ellipse for mean weight and mean girth.

(c) Obtain the 95% Bonferroni confidence intervals for the six means in part (a).

(d) Refer to part (b). Construct the 95% Bonferroni confidence rectangle for mean weight and mean girth using $m = 6$. Compare this rectangle with the simultaneous confidence ellipse in part (b).

(e) Obtain the 95% Bonferroni confidence interval for $(\text{mean head width} - \text{mean head length})$ using $m = 6 + 1 = 7$ to allow for this statement as well as statements about each individual mean.

Enter all the data:
"""

n = 61
p = 6
alpha = 0.05

means = np.array([95.52, 164.38, 55.69, 93.39, 17.98, 31.13])

S = np.array([
    [3266.46, 1343.97, 731.54, 1175.50, 162.68, 238.37],
    [1343.97, 721.91, 324.25, 537.35, 80.17, 117.73],
    [731.54, 324.25, 179.28, 281.17, 39.15, 56.80],
    [1175.50, 537.35, 281.17, 474.98, 63.73, 94.85],
    [162.68, 80.17, 39.15, 63.73, 9.95, 13.88],
    [238.37, 117.73, 56.80, 94.85, 13.88, 21.26]
])

variables = ['Weight (kg)', 'Body length (cm)', 'Neck (cm)', 'Girth (cm)', 'Head length (cm)', 'Head width (cm)']

"""For large samples, a simultaneous confidence interval derived from the multivariate normal confidence region is

$$\bar{x}_i \pm \sqrt{\frac{\chi^2_{p, 1-\alpha} \, s_{ii}}{n}}$$

The important idea is that we don't use a separate ordinary 95% interval for every variable because doing that would not preserve 95% simultaneous confidence across all six means.
"""

# (a)
chi_square_critical = stats.chi2.ppf(1-alpha, df = p)
large_sample_intervals = []

for i in range (p):
  margin = np.sqrt((chi_square_critical * S[i, i]) / n)

  lower = means[i] - margin
  upper = means[i] + margin

  large_sample_intervals.append([lower, upper])

large_sample_intervals = np.array(large_sample_intervals)

results = pd.DataFrame({
    'Variable': variables,
    'Mean': means,
    'Lower': large_sample_intervals[:, 0],
    'Upper': large_sample_intervals[:, 1]
})

results

"""For reusability, we will create a function for confidence ellipses"""

def confidence_ellipse(mean, covariance, n, critical_value,
                       ax, num_points=500):
    """
    Plot a confidence ellipse satisfying

    n * (mu - mean)' S^{-1} (mu - mean)
        <= critical_value
    """

    # Eigenvalues and eigenvectors of covariance matrix
    eigenvalues, eigenvectors = np.linalg.eigh(covariance)

    # Generate a unit circle
    theta = np.linspace(0, 2*np.pi, num_points)

    circle = np.vstack([
        np.cos(theta),
        np.sin(theta)
    ])

    # Scale matrix
    scale = np.sqrt(critical_value / n)

    transformation = (
        eigenvectors
        @ np.diag(np.sqrt(eigenvalues))
        * scale
    )

    ellipse = transformation @ circle

    ellipse[0, :] += mean[0]
    ellipse[1, :] += mean[1]

    ax.plot(ellipse[0, :], ellipse[1, :])
    ax.scatter(mean[0], mean[1])

    return ax

# (b)

indices = [0,3]

mean_wg = means[indices]

S_wg = S[np.ix_(indices, indices)]

print(f'Mean vector for weight and girth:\n {mean_wg}')
print(f'\nCovariance matrix for weight and girth: \n{S_wg}')

chi2_2 = stats.chi2.ppf(0.95, df=2)
fig, ax = plt.subplots(figsize=(8, 6))

confidence_ellipse(
    mean=mean_wg,
    covariance=S_wg,
    n=n,
    critical_value=chi2_2,
    ax=ax
)

ax.set_xlabel("Mean Weight (kg)")
ax.set_ylabel("Mean Girth (cm)")
ax.set_title("95% Confidence Ellipse for Mean Weight and Girth")

ax.grid()
plt.show()

"""The Bonferroni interval is

$$\bar{x}_i \pm t_{n-1, \; 1-\alpha/(2m)} \sqrt{\frac{s_{ii}}{n}}$$

Here, $m = 6$.
"""

m = 6

t_critical = stats.t.ppf(
    1 - alpha / (2 * m),
    df=n - 1
)

bonferroni_intervals = []

for i in range(p):

    standard_error = np.sqrt(S[i, i] / n)

    margin = t_critical * standard_error

    lower = means[i] - margin
    upper = means[i] + margin

    bonferroni_intervals.append([lower, upper])

bonferroni_intervals = np.array(bonferroni_intervals)

bonf_results = pd.DataFrame({
    "Variable": variables,
    "Mean": means,
    "Lower": bonferroni_intervals[:, 0],
    "Upper": bonferroni_intervals[:, 1]
})

bonf_results

# (d)
weight_interval = bonferroni_intervals[0]
girth_interval = bonferroni_intervals[3]

print("Weight:", weight_interval)
print("Girth:", girth_interval)

fig, ax = plt.subplots(figsize=(8, 6))

confidence_ellipse(
    mean_wg,
    S_wg,
    n,
    chi2_2,
    ax
)

rectangle = Rectangle(
    (weight_interval[0], girth_interval[0]),
    weight_interval[1] - weight_interval[0],
    girth_interval[1] - girth_interval[0],
    fill=False,
    linewidth=2
)

ax.add_patch(rectangle)

ax.set_xlabel("Mean Weight (kg)")
ax.set_ylabel("Mean Girth (cm)")
ax.set_title("Confidence Ellipse and Bonferroni Rectangle")
ax.grid()

plt.show()

"""**Comparison**. The Bonferroni rectangle is a "box" that ignores the correlation between Weight and Girth, whereas the ellipse's tilt reflects their strong positive correlation. In this case the rectangle corners stick out past the ellipse in some directions (over-covering there) while cutting into the ellipse along its long axis (under-covering the extreme correlated combinations) — visually you should see the rectangle and ellipse overlapping heavily but not coinciding, which is the typical picture: neither region contains the other in general."""

a = np.array([0, 0, 0, 0, -1, 1])

difference_mean = a @ means

difference_variance = a @ S @ a

print("Mean difference:", difference_mean)
print("Variance:", difference_variance)

m = 7

t_critical_7 = stats.t.ppf(
    1 - alpha/(2*m),
    df=n-1
)

standard_error = np.sqrt(difference_variance / n)

margin = t_critical_7 * standard_error

lower = difference_mean - margin
upper = difference_mean + margin

print('\n Lower and Upper')
print(lower, upper)

"""---

### 3. Mineral Analysis of Ancient Peruvian Hairs

A physical anthropologist performed a mineral analysis of nine ancient Peruvian hairs. The results for chromium ($x_1$) and strontium ($x_2$), in parts per million (ppm), were as follows:

| Observation | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 |
|---|---|---|---|---|---|---|---|---|---|
| **$x_1$ (Cr)** | 0.48 | 40.53 | 2.19 | 0.55 | 0.74 | 0.66 | 0.93 | 0.37 | 0.22 |
| **$x_2$ (St)** | 12.57 | 73.68 | 11.13 | 20.03 | 20.29 | 0.78 | 4.64 | 0.43 | 1.08 |

*Source: Benfer and others, "Mineral Analysis of Ancient Peruvian Hair," American Journal of Physical Anthropology, 48, no. 3 (1978), 277–282.*

It is known that low levels ($\le 0.100\text{ ppm}$) of chromium suggest the presence of diabetes, while strontium is an indication of animal protein intake.

(a) Construct and plot a 90% joint confidence ellipse for the population mean vector $\mathbf{\mu}' = [\mu_1, \mu_2]$, assuming these nine hairs represent a random sample from a particular ancient Peruvian culture.

(b) Obtain the individual simultaneous 90% confidence intervals for $\mu_1$ and $\mu_2$ by projecting the ellipse constructed in part (a) onto each coordinate axis. Does it appear as if this Peruvian culture has a mean strontium level of 10? That is, are any of the points ($\mu_1 \text{ arbitrary}, 10$) in the confidence region? Is $[0.30, 10]'$ a plausible value for $\mathbf{\mu}$? Discuss.

(c) Do these data appear to be bivariate normal? Discuss their status with reference to Q–Q plots and a scatter diagram. If the data are not bivariate normal, what implications does this have for the results in parts (a) and (b)?

(d) Repeat the analysis with the obvious "outlying" observation removed. Do the inferences change? Comment.
"""

hair = np.array([
    [0.48, 12.57],
    [40.53, 73.68],
    [2.19, 11.13],
    [0.55, 20.03],
    [0.74, 20.29],
    [0.66, 0.78],
    [0.93, 4.64],
    [0.37, 0.43],
    [0.22, 1.08]
])

n, p = hair.shape

# sample mean and variance

hair_mean = np.mean(hair, axis = 0)

hair_S = np.cov(hair,
                rowvar = False,
                ddof = 1)

print(f'Mean vector: \n{hair_mean}')
print(f'\nCovariance matrix: \n{hair_S}')

# (a)

alpha = 0.10

critical = (
    p * (n-1) / (n-p) * stats.f.ppf(1-alpha, p, n-p)
)

print(f'Critical: {critical:.4f}')

# plot

fig, ax = plt.subplots(figsize=(8, 6))

confidence_ellipse(
    hair_mean,
    hair_S,
    n,
    critical,
    ax
)

ax.scatter(
    hair[:, 0],
    hair[:, 1]
)

ax.set_xlabel("Chromium (ppm)")
ax.set_ylabel("Strontium (ppm)")
ax.set_title("90% Joint Confidence Ellipse")

ax.grid()
plt.show()

# (b)

intervals = []

for i in range(p):

    margin = np.sqrt(
        critical * hair_S[i, i] / n
    )

    intervals.append([
        hair_mean[i] - margin,
        hair_mean[i] + margin
    ])

intervals = np.array(intervals)

print(intervals)

candidate = np.array([0.30, 10])
difference = hair_mean - candidate

candidate_T2 = (
    n
    * difference.T
    @ np.linalg.inv(hair_S)
    @ difference
)

print(f'{candidate_T2:4f}')
print(f"Critical = {critical:.4f}")

"""Because $1.7725 < 7.4456$, the point $(0.30, 10)$ lies inside the 90% confidence region and is therefore a plausible value for the population mean vector."""

# (c)

plt.figure(figsize=(8, 6))

plt.scatter(
    hair[:, 0],
    hair[:, 1]
)

for i in range(len(hair)):
    plt.annotate(
        str(i + 1),
        (hair[i, 0], hair[i, 1])
    )

plt.xlabel("Chromium")
plt.ylabel("Strontium")
plt.title("Scatter Plot of Chromium vs Strontium")
plt.grid()

plt.show()

# (c)

plt.figure(figsize=(8, 6))

plt.scatter(
    hair[:, 0],
    hair[:, 1]
)

for i in range(len(hair)):
    plt.annotate(
        str(i + 1),
        (hair[i, 0], hair[i, 1])
    )

plt.xlabel("Chromium")
plt.ylabel("Strontium")
plt.title("Scatter Plot of Chromium vs Strontium")
plt.grid()

plt.show()

stats.probplot(
    hair[:, 0],
    dist="norm",
    plot=plt
)

plt.title("Q-Q Plot for Chromium")
plt.show()

stats.probplot(
    hair[:, 1],
    dist="norm",
    plot=plt
)

plt.title("Q-Q Plot for Strontium")
plt.show()

"""**Discussion**. Hair #2 has a chromium level (40.53) and strontium level (73.68) that are far larger than the rest of the sample — in the scatter plot it sits well away from the rest of the cloud, and it produces by far the largest generalized squared distance, causing an obvious departure from the 45° reference line in the chi-square Q–Q plot at the upper end. The univariate Q–Q plots for both variables also show heavy right skew rather than the straight-line pattern expected under normality. Conclusion: the data do not look bivariate normal — there's one clear outlier and noticeable skewness. Since the $T^2$ ellipse and the simultaneous intervals in (a)–(b) rely on a multivariate normal (or large- n) assumption, and here n=9is small and normality is doubtful, those confidence statements should be treated with real caution.

Because this is multivariate data, we can also examine squared Mahalanobis distances.
"""

S_inv = np.linalg.inv(hair_S)

mahalanobis_sq = []

for row in hair:

    d = row - hair_mean

    value = d.T @ S_inv @ d

    mahalanobis_sq.append(value)

mahalanobis_sq = np.sort(mahalanobis_sq)

probabilities = (
    np.arange(1, n + 1) - 0.5
) / n

chi_square_quantiles = stats.chi2.ppf(
    probabilities,
    df=2
)

plt.figure(figsize=(7, 6))

plt.scatter(
    chi_square_quantiles,
    mahalanobis_sq
)

plt.plot(
    chi_square_quantiles,
    chi_square_quantiles
)

plt.xlabel("Chi-square Quantiles")
plt.ylabel("Ordered Squared Mahalanobis Distances")
plt.title("Multivariate Q-Q Plot")

plt.grid()
plt.show()

# (d)
hair_no_outlier = np.delete(
    hair,
    1,
    axis=0
)

hair_no_outlier

n2, p2 = hair_no_outlier.shape

mean2 = np.mean(
    hair_no_outlier,
    axis=0
)

S2 = np.cov(
    hair_no_outlier,
    rowvar=False,
    ddof=1
)

critical2 = (
    p2 * (n2 - 1)
    / (n2 - p2)
    * stats.f.ppf(
        0.90,
        p2,
        n2 - p2
    )
)

print("New mean:")
print(mean2)

print("\nNew covariance:")
print(S2)

fig, ax = plt.subplots(figsize=(8, 6))

confidence_ellipse(
    mean2,
    S2,
    n2,
    critical2,
    ax
)

ax.scatter(
    hair_no_outlier[:, 0],
    hair_no_outlier[:, 1]
)

ax.set_xlabel("Chromium")
ax.set_ylabel("Strontium")
ax.set_title(
    "90% Confidence Ellipse After Removing Outlier"
)

ax.grid()
plt.show()

"""---

### 4. Lumber Strength Measurements

Measurements of $x_1 =$ stiffness (modulus of elasticity) and $x_2 =$ bending strength for a sample of $n = 30$ pieces of a particular grade of lumber are given in the table below. Units are in $\text{lbs/in}^2$.

| $x_1$ (Stiffness) | $x_2$ (Bending strength) | $x_1$ (Stiffness) | $x_2$ (Bending strength) |
|---|---|---|---|
| 1232 | 4175 | 1712 | 7749 |
| 1115 | 6652 | 1932 | 6818 |
| 2205 | 7612 | 1820 | 9307 |
| 1897 | 10914 | 1900 | 6457 |
| 1932 | 10850 | 2426 | 10102 |
| 1612 | 7627 | 1558 | 7414 |
| 1598 | 6954 | 1470 | 7556 |
| 1804 | 8365 | 1858 | 7833 |
| 1752 | 9469 | 1587 | 8309 |
| 2067 | 6410 | 2208 | 9559 |
| 2365 | 10327 | 1487 | 6255 |
| 1646 | 7320 | 2206 | 10723 |
| 1579 | 8196 | 2332 | 5430 |
| 1880 | 9709 | 2540 | 12090 |
| 1773 | 10370 | 2322 | 10072 |

*Source: Data courtesy of U.S. Forest Products Laboratory.*

(a) Construct and sketch a 95% confidence ellipse for the pair $[\mu_1, \mu_2]'$, where $\mu_1 = E(X_1)$ and $\mu_2 = E(X_2)$.

(b) Suppose $\mu_{10} = 2000$ and $\mu_{20} = 10{,}000$ represent "typical" values for stiffness and bending strength, respectively. Given the result in part (a), are the data consistent with these values? Explain.

(c) Is the bivariate normal distribution a viable population model? Explain with reference to Q–Q plots and a scatter diagram.
"""

lumber = np.array([
    [1232, 4175],
    [1115, 6652],
    [2205, 7612],
    [1897, 10914],
    [1932, 10850],
    [1612, 7627],
    [1598, 6954],
    [1804, 8365],
    [1752, 9469],
    [2067, 6410],
    [2365, 10327],
    [1646, 7320],
    [1579, 8196],
    [1880, 9709],
    [1773, 10370],

    [1712, 7749],
    [1932, 6818],
    [1820, 9307],
    [1900, 6457],
    [2426, 10102],
    [1558, 7414],
    [1470, 7556],
    [1858, 7833],
    [1587, 8309],
    [2208, 9559],
    [1487, 6255],
    [2206, 10723],
    [2332, 5430],
    [2540, 12090],
    [2322, 10072]
])

n, p = lumber.shape

lumber_mean = np.mean(
    lumber,
    axis=0
)

lumber_S = np.cov(
    lumber,
    rowvar=False,
    ddof=1
)

print("Mean:")
print(lumber_mean)

print("\nCovariance:")
print(lumber_S)

#(a)
alpha = 0.05

critical_lumber = (
    p * (n - 1)
    / (n - p)
    * stats.f.ppf(
        1-alpha,
        p,
        n-p
    )
)

print(f'Critical Value: {critical_lumber:.4f}')

# plot

fig, ax = plt.subplots(figsize=(8, 6))

confidence_ellipse(
    lumber_mean,
    lumber_S,
    n,
    critical_lumber,
    ax
)

ax.scatter(
    lumber[:, 0],
    lumber[:, 1],
    alpha=0.6
)

ax.set_xlabel("Stiffness")
ax.set_ylabel("Bending Strength")
ax.set_title(
    "95% Confidence Ellipse for Mean Lumber Strength"
)

ax.grid()
plt.show()

#(b)

mu0 = np.array([2000, 10000])

difference = lumber_mean - mu0

T2_typical = (
    n
    * difference.T
    @ np.linalg.inv(lumber_S)
    @ difference
)

print(T2_typical)
print("Critical =", critical_lumber)

if T2_typical > critical:
    print("\n=> T^2 EXCEEDS the critical value: mu0 = (2000, 10000) is OUTSIDE the 95% ellipse.")
    print("   Decision: reject the claim that these are plausible population means.")
else:
    print("\n=> T^2 does NOT exceed the critical value: mu0 = (2000, 10000) is INSIDE the 95% ellipse.")
    print("   Decision: the data ARE consistent with these being the population means.")

F_stat = (
    (n-p)
    /
    (p*(n-1))
    *
    T2_typical
)

p_value = 1 - stats.f.cdf(
    F_stat,
    p,
    n-p
)

print("F =", F_stat)
print("p-value =", p_value)

"""there is very strong evidence against the proposed mean vector."""

fig, ax = plt.subplots(figsize=(8, 6))

confidence_ellipse(
    lumber_mean,
    lumber_S,
    n,
    critical_lumber,
    ax
)

ax.scatter(
    lumber_mean[0],
    lumber_mean[1],
    label="Sample Mean"
)

ax.scatter(
    2000,
    10000,
    marker="x",
    s=100,
    label="Proposed Mean (2000, 10000)"
)

ax.set_xlabel("Mean Stiffness")
ax.set_ylabel("Mean Bending Strength")

ax.set_title(
    "95% Confidence Ellipse with Proposed Mean"
)

ax.legend()
ax.grid()

plt.show()

#(c)

plt.figure(figsize=(8, 6))

plt.scatter(
    lumber[:, 0],
    lumber[:, 1]
)

plt.xlabel("Stiffness")
plt.ylabel("Bending Strength")
plt.title("Scatter Plot of Lumber Measurements")

plt.grid()
plt.show()

stats.probplot(
    lumber[:, 0],
    dist="norm",
    plot=plt
)

plt.title("Q-Q Plot: Stiffness")
plt.show()

stats.probplot(
    lumber[:, 1],
    dist="norm",
    plot=plt
)

plt.title("Q-Q Plot: Bending Strength")
plt.show()

"""**Discussion**. With  n=30points spread fairly evenly and no glaring outliers in the scatter plot, the univariate Q–Q plots for stiffness and bending strength should look reasonably close to straight lines, and the chi-square Q–Q plot of the generalized distances should hug the 45° line reasonably well (check the plots above for any point that strays notably far, particularly in the upper right, which would indicate a departure from bivariate normality). If the points track the reference line closely and the proportion inside the 50% contour is close to 0.50, the bivariate normal model is a reasonable working assumption for this dataset, supporting the validity of the confidence ellipse and $T^2$ test used in parts (a) and (b)."""